### ISSUE TITLE
关于拍照时假死的问题

### ISSUE THREAD

**Issue by Rabbit95** [yangmingchuan/CameraMaster#4]
大佬你好，我在使用你的Camera2（例子）时发现在拍摄某些照片的时候会发生程序假死现象，比如拍摄下面两张照片：
-------------------------照片1-------------------------
![IMG_20191106_152959](https://user-images.githubusercontent.com/34308208/68278981-72960d00-00ad-11ea-9577-2f04fd509115.jpg)
-------------------------照片2-------------------------
![IMG_20191106_154729](https://user-images.githubusercontent.com/34308208/68278986-73c73a00-00ad-11ea-9147-8f5aa3cd67b3.jpg)

在CameraHelper类中的各个方法打上LOG后发现正常完成的拍照会经历以下方法：
takePhone() => capturePhoto() =>OnImageAvailableListener.onImageAvailable() => PhotoSaver异步保存图片 => TakePhotoListener.onTakePhotoFinish()接口返回给调用类。
但是发生假死的拍照操作只经历了：
takePhone() => capturePhoto()
而由CameraCaptureSession.capture()发起的拍照操作进入到了onCaptureCompleted()方法却没有进入到onImageAvailable()中，此时程序表现为：拍照预览卡死，照片没有保存，如果此时将摄像头移至光源正常的环境再点击拍照按钮进行拍照又一切正常，如果此时将应用切换到后台（点击Home键），再切换回应用，控制台会输出以下错误信息：

> 2019-11-06 16:34:12.234 18187-18187/camera.cn.cameramaster W/MessageQueue: Handler (android.os.Handler) {a40c0fc} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {a40c0fc} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:643)
        at android.os.Handler.sendMessageAtTime(Handler.java:612)
        at android.os.Handler.sendMessageDelayed(Handler.java:582)
        at android.os.Handler.post(Handler.java:338)
        at android.hardware.camera2.dispatch.HandlerDispatcher.dispatch(HandlerDispatcher.java:61)
        at android.hardware.camera2.dispatch.MethodNameInvoker.invoke(MethodNameInvoker.java:88)
        at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:177)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl$SequenceDrainListener.onDrained(CameraCaptureSessionImpl.java:678)
        at android.hardware.camera2.utils.TaskDrainer$1.run(TaskDrainer.java:210)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

不知道跟假死问题有没有关系。
这个问题捣鼓了一天也发现不了问题所在，希望大佬能够抽空帮我看看是什么问题，谢谢！

**Comment by Rabbit95** [comment]
补充：
系统版本：Android 7.0
手机型号：厂商定制

**Comment by yangmingchuan** [comment]
很抱歉，暂时没有遇到这个问题。如果onImageAvailable 方法没有返回图片 流的话，确实没有办法往下进行

**Comment by Rabbit95** [comment]
> 很抱歉，暂时没有遇到这个问题。如果onImageAvailable 方法没有返回图片 流的话，确实没有办法往下进行

OK，感谢。
